sensor_msgs/PointCloud2 full_point_cloud
sensor_msgs/PointCloud2 segmented_point_cloud
geometry_msgs/TransformStamped camera_stamped_transform
---
geometry_msgs/PoseStamped[] predicted_grasp_poses
float32[] scores
