sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /head_camera/depth_downsample/free_space_points
    max_range: 1.4
    point_subsample: 1
    padding_offset: 0.06
    padding_scale: 1.0
    max_update_rate: 5.0
    shape_padding: 1.0
    shape_scale: 1.0