FROM coppeliasim:melodic


RUN apt-get update
RUN apt-get install -y ros-melodic-controller-manager ros-melodic-transmission-interface ros-melodic-control-toolbox ros-melodic-joint-limits-interface ros-melodic-cv-bridge
RUN apt-get install -y ros-melodic-depth-image-proc ros-melodic-rail-manipulation-msgs ros-melodic-pcl-conversions ros-melodic-pcl-ros ros-melodic-image-proc