# catkin clean coppeliasim_ros_services coppeliasim_ros_control coppeliasim_msgs_srvs fetch_description robot_controllers fetch_coppeliasim coppeliasim_run fetch_description rail_segmentation
catkin build coppeliasim_ros_services coppeliasim_ros_control coppeliasim_msgs_srvs fetch_description robot_controllers fetch_coppeliasim coppeliasim_run fetch_description coppeliasim_zmq rail_segmentation
