width: 5.0
height: 5.0
resolution: 0.05

plugins:
 - {name: obstacles, type: "costmap_2d::FetchDepthLayer"}
 - {name: inflater,  type: "costmap_2d::InflationLayer"}

obstacles:
  publish_observations: false
