width: 10.0
height: 10.0
resolution: 0.1

plugins:
 - {name: obstacles, type: "costmap_2d::FetchDepthLayer"}
 - {name: inflater,  type: "costmap_2d::InflationLayer"}

obstacles:
  publish_observations: false
