# Base profile
TrajectoryPlannerROS:
  acc_lim_x: 0.075
  acc_lim_y: 0.0
  acc_lim_theta: 1.50
  max_vel_x: 1.075
  min_vel_x: 0.15
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 2.5
  min_vel_theta: -2.5
  min_in_place_vel_theta: 0.75
  holonomic_robot: false

# Recovery behaviors
recovery_behavior_enabled: true
recovery_behaviors:
  - name: "conservative_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
conservative_reset:
  reset_distance: 5.0
